version: '3.8'

services:
  flutter-dev:
    build:
      context: .
      dockerfile: Dockerfile.flutter
    container_name: flutter-dev-env
    volumes:
      - .:/app
      - flutter_cache:/root/.flutter
      - pub_cache:/root/.pub-cache
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      - FLUTTER_ROOT=/opt/flutter
    command: bash

volumes:
  flutter_cache:
  pub_cache: 