// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvM7AHsskCGx43BSaE8OAj_v8sjg59N9o',
    appId: '1:715344161518:web:80f92005af80f0f2b5a1ff',
    messagingSenderId: '715344161518',
    projectId: 'aichatlog-5ade1',
    authDomain: 'aichatlog-5ade1.firebaseapp.com',
    storageBucket: 'aichatlog-5ade1.firebasestorage.app',
    measurementId: 'G-M2YBEGT57F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvM7AHsskCGx43BSaE8OAj_v8sjg59N9o',
    appId: '1:715344161518:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '715344161518',
    projectId: 'aichatlog-5ade1',
    storageBucket: 'aichatlog-5ade1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvM7AHsskCGx43BSaE8OAj_v8sjg59N9o',
    appId: '1:715344161518:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '715344161518',
    projectId: 'aichatlog-5ade1',
    storageBucket: 'aichatlog-5ade1.firebasestorage.app',
    iosBundleId: 'com.example.ailog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvM7AHsskCGx43BSaE8OAj_v8sjg59N9o',
    appId: '1:715344161518:macos:YOUR_MACOS_APP_ID',
    messagingSenderId: '715344161518',
    projectId: 'aichatlog-5ade1',
    storageBucket: 'aichatlog-5ade1.firebasestorage.app',
    iosBundleId: 'com.example.ailog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvM7AHsskCGx43BSaE8OAj_v8sjg59N9o',
    appId: '1:715344161518:windows:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '715344161518',
    projectId: 'aichatlog-5ade1',
    authDomain: 'aichatlog-5ade1.firebaseapp.com',
    storageBucket: 'aichatlog-5ade1.firebasestorage.app',
    measurementId: 'G-M2YBEGT57F',
  );
} 