name: Build & Deploy Flutter Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate .env from GitHub Secrets
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          FIREBASE_IOS_APP_ID: ${{ secrets.FIREBASE_IOS_APP_ID }}
          FIREBASE_IOS_BUNDLE_ID: ${{ secrets.FIREBASE_IOS_BUNDLE_ID }}
          FIREBASE_MACOS_APP_ID: ${{ secrets.FIREBASE_MACOS_APP_ID }}
          FIREBASE_WINDOWS_APP_ID: ${{ secrets.FIREBASE_WINDOWS_APP_ID }}
        run: |
          echo "Creating .env file from secrets"
          cat <<EOF > .env
          FIREBASE_API_KEY=$FIREBASE_API_KEY
          FIREBASE_APP_ID=$FIREBASE_APP_ID
          FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
          FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
          FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
          FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
          FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID
          FIREBASE_ANDROID_APP_ID=$FIREBASE_ANDROID_APP_ID
          FIREBASE_IOS_APP_ID=$FIREBASE_IOS_APP_ID
          FIREBASE_IOS_BUNDLE_ID=$FIREBASE_IOS_BUNDLE_ID
          FIREBASE_MACOS_APP_ID=$FIREBASE_MACOS_APP_ID
          FIREBASE_WINDOWS_APP_ID=$FIREBASE_WINDOWS_APP_ID
          ENVIRONMENT=production
          DEBUG_MODE=false
          MAX_REQUESTS_PER_MINUTE=60
          MAX_REQUESTS_PER_HOUR=1000
          EOF

      - name: Build Flutter web (release)
        run: flutter build web --release --web-renderer html

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-release
          path: build/web 

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          echo "Deploying to Firebase Hosting"
          firebase deploy --only hosting --project $FIREBASE_PROJECT_ID --token "$FIREBASE_TOKEN" --non-interactive 